package plugin

import (
	"encoding/json"
	"fmt"
)

// VerifyMarketplaceEntry checks that marketplace.json contains a plugins[]
// entry whose name matches the given plugin name. It never modifies the file:
// the marketplace listing (including its human-authored description) is owned by
// the maintainer, not generated by ainfra. Returns an error if the file cannot
// be parsed or no matching entry exists.
func VerifyMarketplaceEntry(existing []byte, name string) error {
	var doc struct {
		Plugins []struct {
			Name string `json:"name"`
		} `json:"plugins"`
	}
	if err := json.Unmarshal(existing, &doc); err != nil {
		return fmt.Errorf("plugin: parse marketplace.json: %w", err)
	}
	for _, p := range doc.Plugins {
		if p.Name == name {
			return nil
		}
	}
	return fmt.Errorf("plugin: no marketplace entry named %q in marketplace.json", name)
}
