package lockfile

import (
	"os"

	"gopkg.in/yaml.v3"
)

// Read loads a lockfile. A missing file is not an error: it returns an empty
// v1 lock, so a first run resolves cleanly (spec §7 — both lock files optional).
func Read(path string) (*Lock, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &Lock{Version: 1, Entries: Entries{
			MCPServers:         map[string]Entry{},
			BackgroundServices: map[string]Entry{},
			CLITools:           map[string]Entry{},
		}}, nil
	}
	if err != nil {
		return nil, err
	}
	var l Lock
	if err := yaml.Unmarshal(data, &l); err != nil {
		return nil, err
	}
	return &l, nil
}

// Write serializes a lock to path with a do-not-edit header.
func Write(path string, l *Lock) error {
	data, err := yaml.Marshal(l)
	if err != nil {
		return err
	}
	header := "# Generated by aistack. Do not edit by hand.\n"
	return os.WriteFile(path, append([]byte(header), data...), 0o644)
}
