package lockfile

import (
	"errors"
	"io/fs"
	"os"

	"gopkg.in/yaml.v3"
)

// Read loads a lockfile. A missing file is not an error: it returns an empty
// v1 lock, so a first run resolves cleanly (spec §7 — both lock files optional).
// All Entries channel maps are always non-nil on return, so callers may write
// into them directly even if the file on disk omitted an entries section.
func Read(path string) (*Lock, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return ensureMaps(&Lock{Version: 1}), nil
	}
	if err != nil {
		return nil, err
	}
	var l Lock
	if err := yaml.Unmarshal(data, &l); err != nil {
		return nil, err
	}
	return ensureMaps(&l), nil
}

// ensureMaps initialises any nil Entries channel map so callers can write into
// the returned lock without a nil-map panic.
func ensureMaps(l *Lock) *Lock {
	if l.Entries.MCPServers == nil {
		l.Entries.MCPServers = map[string]Entry{}
	}
	if l.Entries.BackgroundServices == nil {
		l.Entries.BackgroundServices = map[string]Entry{}
	}
	if l.Entries.Hooks == nil {
		l.Entries.Hooks = map[string]Entry{}
	}
	if l.Entries.Commands == nil {
		l.Entries.Commands = map[string]Entry{}
	}
	if l.Entries.CLITools == nil {
		l.Entries.CLITools = map[string]Entry{}
	}
	if l.Entries.Skills == nil {
		l.Entries.Skills = map[string]Entry{}
	}
	if l.Entries.Plugins == nil {
		l.Entries.Plugins = map[string]Entry{}
	}
	if l.Entries.Rules == nil {
		l.Entries.Rules = map[string]Entry{}
	}
	if l.Entries.Tools == nil {
		l.Entries.Tools = map[string]Entry{}
	}
	if l.Secrets == nil {
		l.Secrets = map[string]SecretRef{}
	}
	return l
}

// Write serializes a lock to path with a do-not-edit header.
func Write(path string, l *Lock) error {
	data, err := yaml.Marshal(l)
	if err != nil {
		return err
	}
	header := "# Generated by ainfra. Do not edit by hand.\n"
	return os.WriteFile(path, append([]byte(header), data...), 0o644)
}
